# -*- coding: utf-8 -*-
"""copanova.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16WtXN9wNlpCVhpXcnx1d3eB_Rb5JE69g
"""



import requests
import pandas as pd
import xml.etree.ElementTree as ET
import time
import json
from unidecode import unidecode
from deep_translator import GoogleTranslator

url = "https://www.matchesio.com/competition/world-cup/export/ics/"
data = requests.get(url).text

events = data.split("BEGIN:VEVENT")

rows = []

for event in events[1:]:

    start = None
    summary = None
    location = None

    for line in event.split("\n"):

        if line.startswith("DTSTART"):
            start = line.split(":")[1].strip()

        if line.startswith("SUMMARY"):
            summary = line.split(":",1)[1].strip()

        if line.startswith("LOCATION"):
            location = line.split(":",1)[1].strip()

    rows.append({
        "match": summary,
        "start_raw": start,
        "location": location
    })

df = pd.DataFrame(rows)

df["start"] = pd.to_datetime(df["start_raw"], format="%Y%m%dT%H%M%SZ", errors="coerce")

df["date"] = df["start"].dt.date
df["time"] = df["start"].dt.time

# Robust split: try " - ", " v ", " vs " as separators; fall back to TBD
def split_teams(summary):
    if not isinstance(summary, str):
        return pd.Series(["TBD", "TBD"])
    for sep in [" - ", " v ", " vs "]:
        if sep in summary:
            parts = summary.split(sep, 1)
            home = parts[0].strip() or "TBD"
            away = parts[1].strip() or "TBD"
            return pd.Series([home, away])
    # Single "-" as last resort
    if "-" in summary:
        parts = summary.split("-", 1)
        home = parts[0].strip() or "TBD"
        away = parts[1].strip() or "TBD"
        return pd.Series([home, away])
    return pd.Series([summary.strip() or "TBD", "TBD"])

df[["home_team", "away_team"]] = df["match"].apply(split_teams)

# Normalise known name variants so deduplication works correctly
TEAM_ALIASES = {
    "United States": "USA",
    "Cabo Verde":    "Cape Verde",
    "Cape Verde Islands": "Cape Verde",
    "Korea Republic": "South Korea",
    "IR Iran":        "Iran",
    "Türkiye":        "Turkey",
}
df["home_team"] = df["home_team"].replace(TEAM_ALIASES)
df["away_team"] = df["away_team"].replace(TEAM_ALIASES)

# Drop only rows with no date (bad ICS entries); keep TBD teams
df_calendario = df[df["date"].notna()][
    ["date", "time", "home_team", "away_team", "location"]
].copy()

# Fill remaining NaN fields
df_calendario["home_team"] = df_calendario["home_team"].fillna("TBD")
df_calendario["away_team"] = df_calendario["away_team"].fillna("TBD")
df_calendario["location"]  = df_calendario["location"].fillna("")

# Remove duplicate games (same date + same matchup)
df_calendario = df_calendario.drop_duplicates(
    subset=["date", "home_team", "away_team"]
).reset_index(drop=True)

print(f"Total de jogos após deduplicação: {len(df_calendario)}")

# ── team → ISO-2 country code ─────────────────────────────────────
team_to_country = {
    # Americas
    "Brazil": "BR", "Argentina": "AR", "USA": "US", "Mexico": "MX",
    "Canada": "CA", "Colombia": "CO", "Uruguay": "UY", "Ecuador": "EC",
    "Peru": "PE", "Chile": "CL", "Paraguay": "PY", "Bolivia": "BO",
    "Venezuela": "VE", "Panama": "PA", "Haiti": "HT", "Jamaica": "JM",
    "Costa Rica": "CR", "Honduras": "HN", "El Salvador": "SV",
    "Trinidad and Tobago": "TT", "Cuba": "CU", "Curacao": "CW",
    "Guatemala": "GT", "Suriname": "SR",
    # Europe
    "France": "FR", "Germany": "DE", "Spain": "ES", "Portugal": "PT",
    "England": "GB", "Netherlands": "NL", "Belgium": "BE", "Italy": "IT",
    "Switzerland": "CH", "Croatia": "HR", "Denmark": "DK", "Poland": "PL",
    "Sweden": "SE", "Norway": "NO", "Scotland": "GB-SCT",
    "Austria": "AT", "Czech Republic": "CZ", "Hungary": "HU",
    "Romania": "RO", "Ukraine": "UA", "Serbia": "RS", "Greece": "GR",
    "Slovakia": "SK", "Slovenia": "SI", "Bosnia": "BA", "Iceland": "IS",
    "Finland": "FI", "Ireland": "IE", "Wales": "GB-WLS",
    "Northern Ireland": "GB-NIR", "Albania": "AL", "Bulgaria": "BG",
    "Cyprus": "CY", "Estonia": "EE", "Latvia": "LV", "Lithuania": "LT",
    "Luxembourg": "LU", "Malta": "MT", "Montenegro": "ME",
    "North Macedonia": "MK", "Kosovo": "XK", "Georgia": "GE",
    "Armenia": "AM", "Azerbaijan": "AZ", "Moldova": "MD", "Belarus": "BY",
    # Africa
    "Morocco": "MA", "Nigeria": "NG", "Senegal": "SN", "Ghana": "GH",
    "Cameroon": "CM", "Egypt": "EG", "Tunisia": "TN", "Algeria": "DZ",
    "South Africa": "ZA", "Kenya": "KE", "Ivory Coast": "CI",
    "Cape Verde": "CV", "Mali": "ML", "Burkina Faso": "BF",
    "Guinea": "GN", "Zambia": "ZM", "Tanzania": "TZ", "Angola": "AO",
    "Ethiopia": "ET", "Uganda": "UG", "Mozambique": "MZ",
    "Democratic Republic of Congo": "CD", "Congo": "CG",
    # Asia & Oceania
    "Japan": "JP", "South Korea": "KR", "Australia": "AU",
    "Saudi Arabia": "SA", "Iran": "IR", "Qatar": "QA",
    "United Arab Emirates": "AE", "China": "CN", "India": "IN",
    "Uzbekistan": "UZ", "New Zealand": "NZ", "Philippines": "PH",
    "Thailand": "TH", "Vietnam": "VN", "Malaysia": "MY",
    "Indonesia": "ID", "Oman": "OM", "Bahrain": "BH", "Kuwait": "KW",
    "Jordan": "JO", "Iraq": "IQ", "Syria": "SY", "Lebanon": "LB",
    "Palestine": "PS", "Israel": "IL", "Singapore": "SG",
    "Hong Kong": "HK", "Taiwan": "TW", "Mongolia": "MN",
    "Bangladesh": "BD", "Sri Lanka": "LK", "Nepal": "NP",
    "Afghanistan": "AF", "Pakistan": "PK",
    # aliases / common name variants
    "Korea Republic": "KR", "Korea DPR": "KP", "IR Iran": "IR",
    "United States": "US", "Türkiye": "TR", "Turkey": "TR",
    "Russia": "RU", "Cabo Verde": "CV", "Cape Verde Islands": "CV",
}

# Derive the countries to fetch trends for directly from the calendar teams,
# so every country that actually plays gets included (Jordan, Croatia, Haiti, etc.)
_team_codes = set()
for _, row in df_calendario.iterrows():
    for team in [row["home_team"], row["away_team"]]:
        code = team_to_country.get(team)
        if code:
            # For GB subdivisions (GB-SCT etc.) use the base ISO2
            iso2 = code.split("-")[0]
            _team_codes.add(iso2)

# Also keep the original broad list for richer trends coverage
_base_countries = [
    'AR','AU','AT','BE','BR','CA','CL','CO','CZ','DK','EG','FI','FR','DE',
    'GR','HK','HU','IN','ID','IE','IL','IT','JP','KE','MY','MX','NL','NZ',
    'NG','NO','PE','PH','PL','PT','RO','RU','SA','SG','ZA','KR','ES','SE',
    'CH','TW','TH','TR','UA','AE','GB','US','VN'
]

countries = sorted(set(_base_countries) | _team_codes)
print(f"Países para buscar trends: {countries}")

def get_trends_country(country):

    url = f"https://trends.google.com/trending/rss?geo={country}"
    response = requests.get(url, timeout=10)

    root = ET.fromstring(response.content)

    ns = {'ht': 'https://trends.google.com/trending/rss'}

    data = []

    for pos, item in enumerate(root.findall('./channel/item'), start=1):

        keyword = item.find('title').text
        traffic = item.find('ht:approx_traffic', ns).text
        date = item.find('pubDate').text
        image = item.find('ht:picture', ns).text

        news = item.find('ht:news_item', ns)

        if news is not None:
            news_title = news.find('ht:news_item_title', ns).text
            news_url = news.find('ht:news_item_url', ns).text
        else:
            news_title = None
            news_url = None

        data.append([
            country, pos, keyword, traffic, date,
            news_title, news_url, image
        ])

    return pd.DataFrame(data, columns=[
        'country','position','keyword','traffic','date',
        'news_title','news_url','image_url'
    ])


df_global = pd.DataFrame()

for c in countries:
    try:
        df_country = get_trends_country(c)
        df_global = pd.concat([df_global, df_country], ignore_index=True)
        print("OK", c)
        time.sleep(0.5)
    except Exception as e:
        print("ERRO", c, e)

# ── Translate keywords and news titles to PT-BR ───────────────────
# Collect all unique non-null texts, translate in one batch per chunk,
# then map back — avoids redundant API calls for repeated terms.

def translate_series(series, src='auto', dest='pt', chunk=500):
    """Translate a pandas Series to PT-BR, batching by chunk size."""
    translator = GoogleTranslator(source=src, target=dest)
    unique_texts = series.dropna().unique().tolist()
    translation_map = {}

    for i in range(0, len(unique_texts), chunk):
        batch = unique_texts[i:i + chunk]
        for text in batch:
            try:
                translated = translator.translate(str(text))
                translation_map[text] = translated if translated else text
            except Exception:
                translation_map[text] = text   # keep original on failure
        time.sleep(0.3)  # be polite to the API

    return series.map(lambda x: translation_map.get(x, x) if pd.notna(x) else x)

print("Salvando textos originais...")
df_global["keyword_original"]    = df_global["keyword"]
df_global["news_title_original"] = df_global["news_title"]

print("Traduzindo keywords...")
df_global["keyword"]    = translate_series(df_global["keyword"])

print("Traduzindo títulos de notícias...")
df_global["news_title"] = translate_series(df_global["news_title"])

print("Tradução concluída.")

COUNTRIES_URL = (
    "https://docs.google.com/spreadsheets/d/"
    "1L7gc7wYlDogziA-Uy1l9WFakOBav8KM6"
    "/export?format=xlsx"
)

df_base = pd.read_excel(COUNTRIES_URL)

df_base["country_key"] = df_base["iso2"].astype(str).str.upper()
df_base["country_name_clean"] = df_base["country"].apply(
    lambda x: unidecode(str(x)).lower()
)

df_calendario["date_str"] = df_calendario["date"].astype(str)
df_calendario["time_str"] = df_calendario["time"].astype(str)

events = []

for _, row in df_calendario.iterrows():
    events.append({
        "title": f"{row['home_team']} vs {row['away_team']}",
        "start": f"{row['date_str']}T{row['time_str']}Z",
        "extendedProps": {
            "home_team": row["home_team"],
            "away_team": row["away_team"],
            "home_code": team_to_country.get(row["home_team"]),
            "away_code": team_to_country.get(row["away_team"]),
            "location": row["location"]
        }
    })


df_base_clean = df_base.fillna("").to_dict(orient="records")

trends_by_country = {
    c: g.head(10)[["country","position","keyword","keyword_original",
                   "traffic","date","news_title","news_title_original",
                   "news_url","image_url"]].to_dict(orient="records")
    for c, g in df_global.groupby("country")
}

data_json = {
    "events": events,
    "countries": df_base_clean,
    "trends": trends_by_country
}

html = f"""<!DOCTYPE html>
<html lang="pt-BR">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<title>Copa do Mundo · Dashboard</title>

<link href="https://cdn.jsdelivr.net/npm/fullcalendar@6.1.8/index.global.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"/>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@700;900&family=Source+Serif+4:ital,wght@0,300;0,400;0,600;1,300;1,400&family=DM+Mono:wght@400;500&display=swap" rel="stylesheet">

<style>
  /* ── RESET & BASE ── */
  *, *::before, *::after {{ box-sizing: border-box; margin: 0; padding: 0; }}

  :root {{
    --ink:        #1a1208;
    --paper:      #f0e9d6;
    --paper-dark: #e4d9c0;
    --paper-mid:  #ede3c8;
    --accent:     #8b1a1a;
    --accent2:    #2c4a1e;
    --gold:       #8b6914;
    --muted:      #5c4a2a;
    --rule:       #a8946a;
    --sidebar-bg: #f7f0dc;
    --sidebar-txt:#1a1208;
    --card-bg:    #fdf8ed;
    --sidebar-border: #c8b078;
    --stamp-red:  #8b1a1a;
  }}

  @import url('https://fonts.googleapis.com/css2?family=UnifrakturMaguntia&display=swap');

  html, body {{
    height: 100%;
    background: var(--paper);
    color: var(--ink);
    font-family: 'Source Serif 4', Georgia, serif;
    font-size: 15px;
    line-height: 1.6;
  }}

  /* Paper texture overlay */
  body::before {{
    content: '';
    position: fixed;
    inset: 0;
    pointer-events: none;
    z-index: 9999;
    opacity: .018;
    background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='300' height='300'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='300' height='300' filter='url(%23n)' opacity='1'/%3E%3C/svg%3E");
  }}

  /* ── LAYOUT ── */
  .shell {{
    display: grid;
    grid-template-columns: 1fr 380px;
    grid-template-rows: auto 1fr auto;
    min-height: 100vh;
  }}

  /* Calendar and sidebar fill the middle row completely */
  .cal-panel {{
    grid-column: 1;
    grid-row: 2;
    overflow-y: auto;
  }}

  .sidebar {{
    grid-column: 2;
    grid-row: 2;
  }}

  /* News strip spans full width as third row */
  .news-strip {{
    grid-column: 1 / -1;
    grid-row: 3;
    border-top: 4px double var(--ink);
    background: var(--paper);
  }}

  .news-strip-inner {{
    padding: 20px 28px 28px;
  }}

  .news-strip .section-rule {{
    margin-bottom: 16px;
  }}

  /* Horizontal 2×5 card grid on desktop */
  .news-grid {{
    display: grid;
    grid-template-columns: repeat(5, 1fr);
    grid-template-rows: repeat(2, auto);
    gap: 0;
    border: 1px solid var(--rule);
  }}

  .news-grid .news-card {{
    border-bottom: 1px solid var(--rule);
    border-right: 1px solid var(--rule);
    flex-direction: column;
    display: flex;
    min-height: 200px;
  }}

  /* remove right border on every 5th card */
  .news-grid .news-card:nth-child(5n) {{ border-right: none; }}

  /* remove bottom border on last row (cards 6-10) */
  .news-grid .news-card:nth-child(n+6) {{ border-bottom: none; }}

  .news-grid .news-card .nc-img-wrap {{
    height: 90px;
    border-right: none;
    border-bottom: 1px solid var(--rule);
    flex-shrink: 0;
  }}

  .news-grid .news-card .nc-body {{
    flex: 1;
    padding: 10px 12px;
  }}

  /* News strip placeholder */
  .news-strip-placeholder {{
    padding: 32px;
    text-align: center;
    font-family: 'Playfair Display', serif;
    font-style: italic;
    color: var(--muted);
    font-size: .9rem;
    border: 1px dashed var(--rule);
    margin: 0 28px 28px;
  }}

  /* ── MASTHEAD (old newspaper front page) ── */
  .masthead {{
    grid-column: 1 / -1;
    background: var(--paper);
    color: var(--ink);
    padding: 0;
    border-bottom: 4px double var(--ink);
    position: relative;
  }}

  .masthead-top {{
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 6px 28px 4px;
    border-bottom: 1px solid var(--rule);
    font-family: 'DM Mono', monospace;
    font-size: .6rem;
    letter-spacing: .1em;
    color: var(--muted);
  }}

  .masthead-title {{
    font-family: 'Playfair Display', serif;
    font-size: clamp(1.8rem, 4vw, 3.4rem);
    font-weight: 900;
    letter-spacing: -.5px;
    line-height: 1;
    color: var(--ink);
    text-align: center;
    padding: 10px 28px 6px;
    border-bottom: 1px solid var(--rule);
    text-transform: uppercase;
  }}

  .masthead-title em {{
    font-style: normal;
    color: var(--accent);
  }}

  .masthead-sub {{
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 0;
    padding: 5px 28px;
  }}

  .masthead-sub span {{
    font-family: 'DM Mono', monospace;
    font-size: .62rem;
    letter-spacing: .14em;
    text-transform: uppercase;
    color: var(--muted);
  }}

  .masthead-sub hr {{
    flex: 1;
    border: none;
    border-top: 1px solid var(--rule);
    margin: 0 14px;
  }}

  /* ── CALENDAR PANEL ── */
  .cal-panel {{
    padding: 24px 28px;
    overflow-y: auto;
    background: var(--paper);
    border-right: 2px solid var(--rule);
    align-self: stretch;
  }}

  /* FullCalendar overrides */
  .fc {{
    font-family: 'Source Serif 4', serif;
  }}

  .fc .fc-toolbar-title {{
    font-family: 'Playfair Display', serif;
    font-size: 1.3rem;
    color: var(--ink);
    text-transform: uppercase;
    letter-spacing: .04em;
  }}

  .fc .fc-button {{
    background: var(--ink) !important;
    border: none !important;
    font-family: 'DM Mono', monospace !important;
    font-size: .65rem !important;
    letter-spacing: .08em !important;
    text-transform: uppercase;
    padding: 5px 12px !important;
    border-radius: 1px !important;
    box-shadow: none !important;
    color: var(--paper) !important;
  }}

  .fc .fc-button-primary:not(:disabled).fc-button-active,
  .fc .fc-button-primary:not(:disabled):active {{
    background: var(--accent) !important;
  }}

  .fc .fc-button:hover {{ opacity:.8 !important; }}

  .fc-theme-standard td, .fc-theme-standard th {{
    border-color: var(--rule);
  }}

  .fc .fc-daygrid-day-number {{
    font-family: 'DM Mono', monospace;
    font-size: .72rem;
    color: var(--muted);
    font-weight: 500;
  }}

  .fc .fc-col-header-cell-cushion {{
    font-family: 'DM Mono', monospace;
    font-size: .65rem;
    letter-spacing: .1em;
    text-transform: uppercase;
    color: var(--ink);
    font-weight: 500;
  }}

  .fc .fc-daygrid-day.fc-day-today {{
    background: rgba(139,26,26,.06) !important;
  }}

  /* ── MATCH EVENT CHIP ── */
  .fc-event {{
    background: transparent !important;
    border: none !important;
    padding: 1px 2px !important;
    cursor: pointer;
  }}

  .fc-event:hover .match-chip {{
    background: var(--accent) !important;
    border-color: var(--accent) !important;
    box-shadow: 1px 1px 0 var(--ink) !important;
  }}
  .fc-event:hover .match-chip .vs-badge {{
    color: rgba(255,255,255,.8) !important;
  }}

  .match-chip {{
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 4px;
    background: var(--card-bg);
    border: 1px solid var(--rule);
    border-left: 3px solid var(--accent);
    border-radius: 2px;
    padding: 4px 6px;
    overflow: hidden;
    transition: background .12s, box-shadow .12s;
    cursor: pointer;
    width: 100%;
    box-shadow: 1px 1px 0 rgba(0,0,0,.08);
  }}

  .match-chip .flag-sm {{
    width: 24px;
    height: 16px;
    border-radius: 1px;
    object-fit: cover;
    flex-shrink: 0;
    box-shadow: 0 1px 3px rgba(0,0,0,.25);
  }}

  .match-chip .flag-placeholder {{
    width: 24px;
    height: 16px;
    border-radius: 1px;
    background: var(--rule);
    opacity: .35;
    flex-shrink: 0;
  }}

  .match-chip .tbd-badge {{
    display: inline-flex;
    align-items: center;
    justify-content: center;
    width: 22px;
    height: 15px;
    border-radius: 1px;
    background: var(--paper-dark);
    border: 1px dashed var(--rule);
    font-family: 'DM Mono', monospace;
    font-size: .46rem;
    font-weight: 700;
    color: var(--muted);
    letter-spacing: .04em;
    flex-shrink: 0;
    line-height: 1;
  }}

  .match-chip .vs-badge {{
    font-family: 'DM Mono', monospace;
    font-size: .5rem;
    font-weight: 500;
    color: var(--muted);
    flex-shrink: 0;
    line-height: 1;
  }}

  /* ── SIDEBAR ── */
  .sidebar {{
    background: var(--sidebar-bg);
    color: var(--sidebar-txt);
    overflow-y: auto;
    border-left: 3px double var(--rule);
    display: flex;
    flex-direction: column;
    align-self: stretch;
  }}

  .sidebar-placeholder {{
    flex: 1;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    gap: 16px;
    padding: 40px 24px;
    text-align: center;
  }}

  .sidebar-placeholder svg {{
    opacity: .12;
  }}

  .sidebar-placeholder p {{
    font-family: 'Playfair Display', serif;
    font-size: .95rem;
    font-style: italic;
    color: var(--muted);
    line-height: 1.5;
  }}

  /* ── MATCH HEADER ── */
  .match-header {{
    background: var(--ink);
    padding: 0;
    border-bottom: 4px double var(--rule);
    position: relative;
  }}

  .match-header-banner {{
    background: var(--ink);
    padding: 10px 18px 8px;
    text-align: center;
    border-bottom: 1px solid #333;
  }}

  .match-header-banner .edition-tag {{
    font-family: 'DM Mono', monospace;
    font-size: .58rem;
    letter-spacing: .18em;
    text-transform: uppercase;
    color: var(--rule);
    display: block;
    margin-bottom: 6px;
  }}

  .match-header .kickoff {{
    font-family: 'DM Mono', monospace;
    font-size: .62rem;
    letter-spacing: .12em;
    text-transform: uppercase;
    color: var(--paper-dark);
    opacity: .7;
  }}

  .match-versus {{
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 12px;
    padding: 14px 18px;
    background: var(--ink);
  }}

  .team-block {{
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 8px;
    flex: 1;
    cursor: pointer;
    padding: 10px 8px;
    border: 1px solid transparent;
    border-radius: 2px;
    transition: border-color .15s, background .15s;
  }}

  .team-block:hover {{ border-color: var(--rule); background: rgba(255,255,255,.05); }}
  .team-block.active {{
    border-color: var(--accent);
    background: rgba(139,26,26,.12);
    outline: none;
  }}

  .team-block img.flag-lg {{
    width: 54px;
    height: 36px;
    border-radius: 2px;
    object-fit: cover;
    box-shadow: 2px 2px 0 rgba(0,0,0,.5);
  }}

  .team-block .team-label {{
    font-family: 'Playfair Display', serif;
    font-size: .85rem;
    color: var(--paper-dark);
    text-align: center;
    line-height: 1.2;
    font-style: italic;
  }}

  .vs-divider {{
    font-family: 'Playfair Display', serif;
    font-size: 1.5rem;
    color: var(--accent);
    font-weight: 900;
    flex-shrink: 0;
    text-shadow: 1px 1px 0 rgba(0,0,0,.4);
  }}

  .match-venue {{
    font-family: 'DM Mono', monospace;
    font-size: .58rem;
    letter-spacing: .1em;
    color: var(--rule);
    text-align: center;
    padding: 6px 18px 12px;
    background: var(--ink);
    text-transform: uppercase;
  }}

  /* ── COUNTRY MAP ── */
  .country-map-wrap {{
    position: relative;
    height: 200px;
    border-bottom: 3px double var(--rule);
    overflow: hidden;
  }}

  #country-map {{
    width: 100%;
    height: 100%;
  }}

  .map-label {{
    position: absolute;
    top: 10px;
    left: 12px;
    z-index: 500;
    background: rgba(240,233,214,.9);
    color: var(--accent);
    font-family: 'Playfair Display', serif;
    font-size: .7rem;
    font-style: italic;
    padding: 3px 10px;
    border: 1px solid var(--rule);
    pointer-events: none;
    box-shadow: 1px 1px 0 rgba(0,0,0,.1);
  }}

  /* Leaflet controls - newspaper style */
  .leaflet-control-zoom a {{
    background: var(--paper) !important;
    color: var(--ink) !important;
    border-color: var(--rule) !important;
    font-family: 'DM Mono', monospace !important;
    font-weight: 500 !important;
  }}
  .leaflet-control-zoom a:hover {{ background: var(--paper-dark) !important; }}
  .leaflet-control-attribution {{
    font-size: .42rem !important;
    opacity: .5;
    background: rgba(240,233,214,.7) !important;
    color: var(--muted) !important;
  }}
  .leaflet-control-attribution a {{ color: var(--muted) !important; }}

  /* ── COUNTRY INFO ── */
  .country-info {{
    padding: 16px 20px 0;
    border-bottom: 2px double var(--rule);
  }}

  .country-info h3 {{
    font-family: 'Playfair Display', serif;
    font-size: 1.5rem;
    font-weight: 900;
    color: var(--ink);
    margin-bottom: 4px;
    text-transform: uppercase;
    letter-spacing: .02em;
    border-bottom: 1px solid var(--rule);
    padding-bottom: 8px;
  }}

  .geo-grid {{
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 0;
    margin-bottom: 0;
    border: 1px solid var(--rule);
    border-top: none;
    margin-bottom: 16px;
  }}

  .geo-item {{
    padding: 8px 12px;
    border-right: 1px solid var(--rule);
    border-bottom: 1px solid var(--rule);
  }}

  .geo-item:nth-child(even) {{ border-right: none; }}

  .geo-item .geo-label {{
    font-family: 'DM Mono', monospace;
    font-size: .55rem;
    letter-spacing: .14em;
    text-transform: uppercase;
    color: var(--muted);
    margin-bottom: 2px;
  }}

  .geo-item .geo-val {{
    font-family: 'Source Serif 4', serif;
    font-size: .88rem;
    color: var(--ink);
    font-weight: 600;
  }}

  /* ── SECTION RULE ── */
  .section-rule {{
    display: flex;
    align-items: center;
    gap: 10px;
    margin-bottom: 14px;
  }}

  .section-rule span {{
    font-family: 'Playfair Display', serif;
    font-size: .95rem;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: .04em;
    color: var(--ink);
    white-space: nowrap;
  }}

  .section-rule .rule-line {{
    flex: 1;
    height: 3px;
    background: linear-gradient(to right, var(--ink), transparent);
  }}

  /* ── NEWS CARD (shared styles, layout overridden per context) ── */
  .news-card {{
    background: var(--card-bg);
    transition: background .12s;
    overflow: hidden;
  }}

  .news-card:hover {{ background: var(--paper-mid); }}

  .news-card .nc-img-wrap {{
    position: relative;
    overflow: hidden;
    background: var(--paper-dark);
  }}

  .news-card .nc-img {{
    width: 100%;
    height: 100%;
    object-fit: cover;
    display: block;
    filter: sepia(12%) contrast(1.02);
    transition: transform .3s;
  }}

  .news-card:hover .nc-img {{ transform: scale(1.04); }}

  .news-card .nc-img-placeholder {{
    width: 100%;
    height: 100%;
    display: flex;
    align-items: center;
    justify-content: center;
    font-family: 'Playfair Display', serif;
    font-size: 2rem;
    color: var(--rule);
    opacity: .5;
  }}

  .news-card .nc-rank-badge {{
    position: absolute;
    top: 0;
    left: 0;
    background: var(--accent);
    color: #fff;
    font-family: 'DM Mono', monospace;
    font-size: .58rem;
    font-weight: 700;
    padding: 2px 6px;
    letter-spacing: .06em;
  }}

  .news-card .nc-body {{
    padding: 10px 12px;
    display: flex;
    flex-direction: column;
    justify-content: space-between;
    gap: 4px;
    min-width: 0;
  }}

  .news-card .nc-volume {{
    font-family: 'DM Mono', monospace;
    font-size: .58rem;
    letter-spacing: .1em;
    text-transform: uppercase;
    color: var(--accent);
    font-weight: 600;
  }}

  .news-card .nc-keyword {{
    font-family: 'Playfair Display', serif;
    font-size: 1rem;
    font-weight: 700;
    color: var(--ink);
    line-height: 1.2;
    text-transform: capitalize;
  }}

  .news-card .nc-headline {{
    font-family: 'Source Serif 4', serif;
    font-size: .72rem;
    color: var(--muted);
    line-height: 1.4;
    display: -webkit-box;
    -webkit-line-clamp: 3;
    -webkit-box-orient: vertical;
    overflow: hidden;
    text-decoration: none;
    font-style: italic;
  }}

  .news-card .nc-headline:hover {{ color: var(--accent); }}

  .news-card .nc-read-more {{
    font-family: 'DM Mono', monospace;
    font-size: .54rem;
    letter-spacing: .1em;
    text-transform: uppercase;
    color: var(--rule);
    text-decoration: none;
    align-self: flex-start;
    border-bottom: 1px solid var(--rule);
    transition: color .12s, border-color .12s;
  }}

  .news-card .nc-read-more:hover {{
    color: var(--accent);
    border-color: var(--accent);
  }}

  /* ── SCROLLBAR ── */
  .sidebar::-webkit-scrollbar {{ width: 5px; }}
  .sidebar::-webkit-scrollbar-track {{ background: var(--paper-dark); }}
  .sidebar::-webkit-scrollbar-thumb {{ background: var(--rule); border-radius: 0; }}

  /* ── RESPONSIVE ── */
  @media (max-width: 900px) {{
    .shell {{
      grid-template-columns: 1fr;
      grid-template-rows: auto 1fr auto auto;
    }}
    .cal-panel {{
      grid-column: 1; grid-row: 2;
      padding: 16px 14px;
      border-right: none;
      border-bottom: 3px double var(--rule);
    }}
    .sidebar {{
      grid-column: 1; grid-row: 3;
      border-left: none;
      border-top: 3px double var(--rule);
    }}
    .news-strip {{
      grid-column: 1; grid-row: 4;
    }}
    /* News strip stacks to 2 columns on tablet */
    .news-grid {{
      grid-template-columns: repeat(2, 1fr) !important;
    }}
    .news-grid .news-card {{ border-bottom: 1px solid var(--rule); border-right: 1px solid var(--rule); }}
    .news-grid .news-card:nth-child(2n) {{ border-right: none; }}
    .news-grid .news-card:nth-child(5n) {{ border-right: 1px solid var(--rule); }}
    .news-grid .news-card:last-child {{ border-right: none; border-bottom: none; }}
    .news-grid .news-card:nth-last-child(2):nth-child(odd) {{ border-bottom: none; }}
    .masthead-top {{ padding: 5px 16px 4px; }}
    .masthead-title {{ font-size: 1.9rem; padding: 8px 16px 5px; }}
    .masthead-sub {{ padding: 4px 16px; }}
  }}

  @media (max-width: 600px) {{
    .masthead-title {{ font-size: 1.4rem; }}
    .cal-panel {{ padding: 10px 8px; }}
    .fc .fc-toolbar {{ flex-wrap: wrap; gap: 5px; }}
    .fc .fc-toolbar-title {{ font-size: .9rem; }}
    .fc .fc-button {{ font-size: .58rem !important; padding: 4px 9px !important; }}
    .fc .fc-daygrid-day-number {{ font-size: .58rem; }}
    .fc .fc-col-header-cell-cushion {{ font-size: .58rem; }}
    .match-chip {{ padding: 3px 5px; gap: 3px; }}
    .match-chip .flag-sm {{ width: 18px; height: 12px; }}
    .match-chip .flag-placeholder {{ width: 18px; height: 12px; }}
    .match-chip .vs-badge {{ font-size: .42rem; }}
    .match-versus {{ padding: 10px 12px; gap: 8px; }}
    .team-block img.flag-lg {{ width: 42px; height: 28px; }}
    .vs-divider {{ font-size: 1.1rem; }}
    .country-map-wrap {{ height: 160px; }}
    /* Single column on mobile */
    .news-grid {{
      grid-template-columns: 1fr !important;
    }}
    .news-grid .news-card {{ border-right: none !important; }}
    .news-grid .news-card .nc-img-wrap {{ height: 80px; }}
    .country-info h3 {{ font-size: 1.2rem; }}
    .news-strip-inner {{ padding: 14px 14px 20px; }}
  }}

  @media (max-width: 380px) {{
    .match-chip .vs-badge {{ display: none; }}
    .masthead-title {{ font-size: 1.15rem; }}
  }}

  /* ── LANGUAGE TOGGLE BAR ── */
  .lang-bar {{
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 10px;
    padding: 6px 28px 7px;
    background: var(--paper-dark);
    border-top: 1px solid var(--rule);
  }}
  .lang-label {{
    font-family: 'DM Mono', monospace;
    font-size: .6rem;
    letter-spacing: .12em;
    text-transform: uppercase;
    color: var(--muted);
  }}
  .lang-btn {{
    font-family: 'DM Mono', monospace;
    font-size: .62rem;
    letter-spacing: .1em;
    text-transform: uppercase;
    padding: 4px 14px;
    border: 1px solid var(--rule);
    background: transparent;
    color: var(--muted);
    cursor: pointer;
    border-radius: 1px;
    transition: background .12s, color .12s, border-color .12s;
  }}
  .lang-btn:hover {{
    background: var(--paper-mid);
    color: var(--ink);
    border-color: var(--ink);
  }}
  .lang-btn.active {{
    background: var(--ink);
    color: var(--paper);
    border-color: var(--ink);
  }}
</style>
</head>

<body>
<div class="shell">

  <!-- MASTHEAD -->
  <header class="masthead">
    <div class="masthead-top">
      <span>Fundado em 2026 · Edição Especial</span>
      <span id="today-date"></span>
      <span>Tendências &amp; Esportes · Edição Mundial</span>
    </div>
    <div class="masthead-title">⚽ A <em>Gazeta</em> da Copa</div>
    <div class="masthead-sub">
      <hr>
      <span>Calendário Oficial &nbsp;·&nbsp; Tendências de Busca &nbsp;·&nbsp; Dados Geográficos</span>
      <hr>
    </div>
    <div class="lang-bar">
      <span class="lang-label">Idioma das tendências:</span>
      <button class="lang-btn active" id="btn-pt" onclick="setLang('pt')">🇧🇷 Português</button>
      <button class="lang-btn" id="btn-orig" onclick="setLang('orig')">🌐 Original</button>
    </div>
  </header>

  <!-- CALENDAR -->
  <main class="cal-panel">
    <div id="calendar"></div>
  </main>

  <!-- SIDEBAR -->
  <aside class="sidebar" id="sidebar">
    <div class="sidebar-placeholder" id="placeholder">
      <svg width="60" height="60" viewBox="0 0 60 60" fill="none">
        <circle cx="30" cy="30" r="28" stroke="#a8946a" stroke-width="1.5" stroke-dasharray="4 3"/>
        <path d="M30 10 L33 21 L44 21 L35 28 L38 39 L30 32 L22 39 L25 28 L16 21 L27 21 Z" fill="#a8946a"/>
      </svg>
      <p><em>Selecione uma partida<br>no calendário para<br>ler a edição do dia</em></p>
    </div>
    <div id="match-detail" style="display:none;"></div>
  </aside>

  <!-- NEWS STRIP -->
  <section class="news-strip">
    <div class="news-strip-inner">
      <div class="section-rule">
        <span id="news-strip-title">Tendências do Dia</span>
        <div class="rule-line"></div>
      </div>
      <div id="news-strip-content">
        <div class="news-strip-placeholder">
          <em>As tendências de busca do país selecionado aparecerão aqui após clicar em um jogo.</em>
        </div>
      </div>
    </div>
  </section>

</div>

<script src="https://cdn.jsdelivr.net/npm/fullcalendar@6.1.8/index.global.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@fullcalendar/core@6.1.8/locales/pt-br.global.min.js"></script>
<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script>

<script>
// ── DATA ──────────────────────────────────────────────────────────
const DATA = {json.dumps(data_json, ensure_ascii=False)};

const countryMap = {{}};
DATA.countries.forEach(c => countryMap[c.country_key] = c);

// ── COUNTRY COORDINATES ───────────────────────────────────────────
const COORDS = {{
  AF:[33,65],AL:[41,20],DZ:[28,3],AO:[-12,18],AR:[-34,-64],AM:[40,45],
  AU:[-25,134],AT:[47,14],AZ:[40,48],BE:[50,4],BR:[-10,-55],CA:[56,-96],
  CL:[-35,-71],CN:[35,105],CO:[4,-74],CZ:[50,15],DK:[56,10],EG:[27,30],
  ET:[9,39],FI:[64,26],FR:[46,2],DE:[51,10],GH:[8,-1],GR:[39,22],
  HK:[22,114],HU:[47,19],IN:[20,77],ID:[-5,120],IE:[53,-8],IL:[31,35],
  IT:[42,12],JP:[36,138],KE:[-1,38],MY:[4,109],MX:[23,-102],MA:[32,-6],
  NL:[52,5],NZ:[-41,174],NG:[10,8],NO:[60,8],PE:[-10,-76],PH:[13,122],
  PL:[52,20],PT:[39,-8],RO:[46,25],RU:[60,100],SA:[24,45],SN:[14,-14],
  SG:[1,104],ZA:[-29,25],KR:[36,128],ES:[40,-4],SE:[62,15],CH:[47,8],
  TW:[24,121],TH:[15,101],TR:[39,35],UA:[49,32],AE:[24,54],GB:[55,-3],
  US:[38,-97],VN:[16,108],UY:[-33,-56],EC:[-2,-77],PY:[-23,-58],
  BO:[-17,-65],VE:[8,-66],TN:[34,9],CM:[6,12],CI:[7,-5],SN:[14,-14],
  RS:[44,21],HR:[45,16],SK:[48,19],SI:[46,15],BA:[44,17],ME:[42,19],
  MK:[41,22],AL:[41,20],MT:[36,14],CY:[35,33],LU:[49,6],EE:[59,25],
  LV:[57,25],LT:[56,24],FI:[64,26],IS:[65,-18],
}};

// ── LEAFLET MAP INSTANCE ──────────────────────────────────────────
let leafletMap = null;
let leafletMarker = null;

// ── HELPERS ───────────────────────────────────────────────────────
function flag(code) {{
  if (!code) return '';
  // flagcdn supports subdivision codes like gb-sct, gb-eng, gb-wls
  return `https://flagcdn.com/w80/${{code.toLowerCase()}}.png`;
}}

function flagOrTbd(code, team) {{
  if (!code || team === 'TBD') {{
    return `<div style="
      width:54px;height:36px;border-radius:2px;
      background:var(--paper-dark);border:1px dashed var(--rule);
      display:flex;align-items:center;justify-content:center;
      font-family:'DM Mono',monospace;font-size:.6rem;
      color:var(--muted);font-weight:700;letter-spacing:.06em;">TBD</div>`;
  }}
  return `<img class="flag-lg" src="https://flagcdn.com/w80/${{code.toLowerCase()}}.png"
               onerror="this.outerHTML=flagOrTbd(null,'TBD')" style="width:54px;height:36px;border-radius:2px;object-fit:cover;box-shadow:2px 2px 0 rgba(0,0,0,.5);">`;
}}

function fmt(val) {{
  if (val === '' || val === null || val === undefined) return '—';
  if (typeof val === 'number') return val.toLocaleString('pt-BR');
  return val;
}}

// ── TODAY DATE ────────────────────────────────────────────────────
document.getElementById('today-date').textContent =
  new Date().toLocaleDateString('pt-BR', {{ weekday:'long', year:'numeric', month:'long', day:'numeric' }});

// ── LANGUAGE STATE ────────────────────────────────────────────────
let currentLang = 'pt'; // 'pt' | 'orig'

function setLang(lang) {{
  currentLang = lang;
  document.getElementById('btn-pt').classList.toggle('active', lang === 'pt');
  document.getElementById('btn-orig').classList.toggle('active', lang === 'orig');
  // Re-render news strip if a country is already active
  if (activeTeamEl) {{
    const code = activeTeamEl.id === 'btn-home'
      ? activeTeamEl.closest('#match-detail') && document.querySelector('#btn-home') && activeTeamEl._countryCode
      : activeTeamEl._countryCode;
    if (activeTeamEl._countryCode) renderTrends(activeTeamEl._countryCode);
  }}
}}

// ── RENDER COUNTRY PANEL ──────────────────────────────────────────
let activeTeamEl = null;

function renderTrends(code) {{
  const trendsCode = (code && code.startsWith('GB-')) ? 'GB' : code;
  const trends = DATA.trends[trendsCode] || [];
  const tb = document.getElementById('news-strip-content');
  const titleEl = document.getElementById('news-strip-title');
  const c = countryMap[code] || {{}};
  if (!tb) return;
  if (titleEl) titleEl.textContent = `Trending · ${{c.country || code}}`;
  if (!trends.length) {{
    tb.innerHTML = `<div class="news-strip-placeholder"><em>Sem dados de tendências disponíveis para este país.</em></div>`;
    return;
  }}
  function buildCard(item) {{
    const keyword   = currentLang === 'orig' ? (item.keyword_original   || item.keyword)   : item.keyword;
    const newsTitle = currentLang === 'orig' ? (item.news_title_original || item.news_title) : item.news_title;
    const imgHtml = item.image_url
      ? `<img class="nc-img" src="${{item.image_url}}" onerror="this.parentElement.innerHTML='<div class=\\'nc-img-placeholder\\'>📰</div>'">`
      : `<div class="nc-img-placeholder">📰</div>`;
    const headlineHtml = item.news_url
      ? `<a class="nc-headline" href="${{item.news_url}}" target="_blank">${{newsTitle || ''}}</a>`
      : (newsTitle ? `<span class="nc-headline">${{newsTitle}}</span>` : '');
    const readMoreHtml = item.news_url
      ? `<a class="nc-read-more" href="${{item.news_url}}" target="_blank">Ler mais →</a>`
      : '';
    return `
      <div class="news-card">
        <div class="nc-img-wrap">
          ${{imgHtml}}
          <span class="nc-rank-badge">#${{item.position}}</span>
        </div>
        <div class="nc-body">
          <div class="nc-volume">▲ ${{item.traffic}} buscas</div>
          <div class="nc-keyword">${{keyword}}</div>
          ${{headlineHtml}}
          ${{readMoreHtml}}
        </div>
      </div>`;
  }}
  tb.innerHTML = `<div class="news-grid">${{trends.map(buildCard).join('')}}</div>`;
}}

function renderCountry(code, teamEl) {{
  if (!code || code === 'TBD') {{
    // Nothing to show for TBD teams
    if (activeTeamEl) activeTeamEl.classList.remove('active');
    if (teamEl) {{ teamEl.classList.add('active'); activeTeamEl = teamEl; }}
    const geo = document.getElementById('geo-block');
    if (geo) geo.innerHTML = `
      <div style="padding:24px 20px;text-align:center;font-family:'Playfair Display',serif;
                  font-style:italic;color:var(--muted);font-size:.9rem;border-bottom:1px solid var(--rule);">
        Time ainda não definido
      </div>`;
    const tb = document.getElementById('news-strip-content');
    if (tb) tb.innerHTML = `<div class="news-strip-placeholder"><em>Time a definir — tendências indisponíveis.</em></div>`;
    return;
  }}
  if (activeTeamEl) activeTeamEl.classList.remove('active');
  if (teamEl) {{ teamEl.classList.add('active'); activeTeamEl = teamEl; teamEl._countryCode = code; }}

  const c = countryMap[code] || {{}};
  // GB subdivisions (GB-SCT, GB-ENG, GB-WLS, GB-NIR) use UK trends
  const trendsCode = (code && code.startsWith('GB-')) ? 'GB' : code;
  const trends = DATA.trends[trendsCode] || [];

  // Country info block — includes map container
  const geo = document.getElementById('geo-block');
  if (geo) {{
    geo.innerHTML = `
      <div class="country-map-wrap">
        <div id="country-map"></div>
        <div class="map-label">📍 ${{c.country || code}}</div>
      </div>
      <div class="country-info">
        <h3>${{c.country || code}}</h3>
        <div class="geo-grid">
          <div class="geo-item">
            <div class="geo-label">População</div>
            <div class="geo-val">${{fmt(c.population)}}</div>
          </div>
          <div class="geo-item">
            <div class="geo-label">PIB</div>
            <div class="geo-val">${{fmt(c.gdp)}}</div>
          </div>
          <div class="geo-item">
            <div class="geo-label">Continente</div>
            <div class="geo-val">${{fmt(c.continent)}}</div>
          </div>
          <div class="geo-item">
            <div class="geo-label">Idioma</div>
            <div class="geo-val">${{fmt(c.language)}}</div>
          </div>
          <div class="geo-item">
            <div class="geo-label">Moeda</div>
            <div class="geo-val">${{fmt(c.currency)}}</div>
          </div>
          <div class="geo-item">
            <div class="geo-label">Religião</div>
            <div class="geo-val">${{fmt(c.religion)}}</div>
          </div>
        </div>
      </div>
    `;

    // Init or update Leaflet map
    const coords = COORDS[code];
    if (leafletMap) {{
      leafletMap.remove();
      leafletMap = null;
      leafletMarker = null;
    }}

    leafletMap = L.map('country-map', {{
      zoomControl: true,
      attributionControl: true,
      dragging: true,
      scrollWheelZoom: false,
      doubleClickZoom: true,
      touchZoom: true,
    }});

    L.tileLayer(
      'https://{{s}}.basemaps.cartocdn.com/rastertiles/voyager/{{z}}/{{x}}/{{y}}{{r}}.png',
      {{ attribution: '© OpenStreetMap © CARTO', subdomains: 'abcd', maxZoom: 10 }}
    ).addTo(leafletMap);

    if (coords) {{
      leafletMap.setView(coords, 4);
      const pulseIcon = L.divIcon({{
        className: '',
        html: `<div style="
          width:14px;height:14px;border-radius:50%;
          background:${{getComputedStyle(document.documentElement).getPropertyValue('--accent').trim() || '#c0392b'}};
          border:3px solid #fff;
          box-shadow:0 0 0 4px rgba(192,57,43,.35), 0 0 12px rgba(192,57,43,.5);
        "></div>`,
        iconSize: [14, 14],
        iconAnchor: [7, 7],
      }});
      leafletMarker = L.marker(coords, {{icon: pulseIcon}}).addTo(leafletMap);
    }} else {{
      leafletMap.setView([20, 0], 2);
    }}
  }}

  // ── Render trends into the full-width news strip ─────────────────
  renderTrends(code);
}}

// ── RENDER MATCH ──────────────────────────────────────────────────
function renderMatch(info) {{
  const ep = info.event.extendedProps;
  const home = ep.home_code;
  const away = ep.away_code;
  const homeTeam = ep.home_team;
  const awayTeam = ep.away_team;
  const loc = ep.location || '';
  const dt = new Date(info.event.start);
  const dtStr = dt.toLocaleString('pt-BR', {{
    weekday:'short', day:'2-digit', month:'short',
    hour:'2-digit', minute:'2-digit', timeZone:'America/Sao_Paulo'
  }});

  document.getElementById('placeholder').style.display = 'none';
  const detail = document.getElementById('match-detail');
  detail.style.display = 'block';

  detail.innerHTML = `
    <div class="match-header">
      <div class="match-header-banner">
        <span class="edition-tag">⚽ Confronto da Rodada</span>
        <div class="kickoff">⏱ ${{dtStr}} BRT</div>
      </div>
      <div class="match-versus">
        <div class="team-block" id="btn-home" onclick="renderCountry('${{home}}', this)">
          ${{flagOrTbd(home, homeTeam)}}
          <div class="team-label">${{homeTeam}}</div>
        </div>
        <div class="vs-divider">VS</div>
        <div class="team-block" id="btn-away" onclick="renderCountry('${{away}}', this)">
          ${{flagOrTbd(away, awayTeam)}}
          <div class="team-label">${{awayTeam}}</div>
        </div>
      </div>
      ${{loc ? `<div class="match-venue">📍 ${{loc}}</div>` : ''}}
    </div>

    <div id="geo-block"></div>
  `;

  // Auto-load home team
  activeTeamEl = null;
  renderCountry(home, document.getElementById('btn-home'));
}}

// ── CALENDAR ──────────────────────────────────────────────────────
document.addEventListener('DOMContentLoaded', function() {{
  const calEl = document.getElementById('calendar');

  const calendar = new FullCalendar.Calendar(calEl, {{
    initialView: 'dayGridMonth',
    locale: 'pt-br',
    initialDate: '2026-06-01',
    headerToolbar: {{
      left: 'prev,next today',
      center: 'title',
      right: ''
    }},
    height: 'auto',
    eventContent: function(arg) {{
      const ep = arg.event.extendedProps;
      const home = ep.home_code;
      const away = ep.away_code;
      const homeTeam = ep.home_team || home || '?';
      const awayTeam = ep.away_team || away || '?';

      // Use flagcdn with TBD fallback — subdivision codes (gb-sct, gb-eng) are supported
      function flagImg(code, team) {{
        if (!code || team === 'TBD' || team === '') {{
          return `<span class="tbd-badge" title="A definir">?</span>`;
        }}
        return `<img class="flag-sm" src="https://flagcdn.com/w80/${{code.toLowerCase()}}.png"
                     title="${{team}}"
                     onerror="this.outerHTML='<span class=\\'tbd-badge\\' title=\\'${{team}}\\'>?</span>'">`;
      }}

      const chip = document.createElement('div');
      chip.className = 'match-chip';
      chip.innerHTML = `
        ${{flagImg(home, homeTeam)}}
        <span class="vs-badge">×</span>
        ${{flagImg(away, awayTeam)}}
      `;

      return {{ domNodes: [chip] }};
    }},
    eventClick: renderMatch,
    eventMouseEnter: function(info) {{
      info.el.style.zIndex = '10';
    }},
    eventMouseLeave: function(info) {{
      info.el.style.zIndex = '';
    }},
    events: DATA.events
  }});

  calendar.render();
}});
</script>
</body>
</html>"""

with open("index.html", "w", encoding="utf-8") as f:
    f.write(html)

print("HTML gerado com sucesso!")
